# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-03 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='outgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(default=b'0000000')),
                ('engg_name', models.CharField(default=b'Enter Engineer Name', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=b'0000000')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 4, 3, 8, 34, 49, 71766))),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 8, 34, 49, 71035)),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=b'0000000'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cetagory',
            field=models.CharField(default=b'Enter Category', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=b'Enter Description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=b'Enter Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(default=b'Enter Supplier', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(default=b'0000000'),
        ),
    ]
