# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-03 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190403_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 10, 16, 58, 600806)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 10, 16, 58, 600272)),
        ),
    ]
