# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-12 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190403_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cetagory', models.CharField(max_length=200)),
                ('supplier', models.CharField(max_length=200)),
                ('unit_price', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 4, 12, 8, 54, 11, 150125))),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 8, 54, 11, 150854)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 8, 54, 11, 149453)),
        ),
    ]
