# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-12 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190412_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 11, 30, 31, 243075)),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 11, 30, 31, 243772)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 11, 30, 31, 242457)),
        ),
    ]
