# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-07 14:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190412_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 14, 1, 11, 28363)),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 14, 1, 11, 28984)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 14, 1, 11, 27770)),
        ),
    ]
