# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-13 08:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190507_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 8, 26, 53, 121964)),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 8, 26, 53, 122480)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 8, 26, 53, 121121)),
        ),
    ]
