# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-15 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20190513_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 14, 23, 4, 450395)),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 14, 23, 4, 451138)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 14, 23, 4, 449712)),
        ),
    ]
