# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-18 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20190515_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 17, 28, 15, 528823)),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 17, 28, 15, 529506)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 17, 28, 15, 528122)),
        ),
    ]
