# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-19 08:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20190518_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='outgoing_supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('engg_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 5, 19, 8, 57, 12, 571519))),
            ],
        ),
        migrations.DeleteModel(
            name='outgoing',
        ),
        migrations.AlterField(
            model_name='incoming',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 8, 57, 12, 570839)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 8, 57, 12, 569748)),
        ),
    ]
